#!/usr/bin/env bash

# TODO - if config exists, overwrite?
config_path=~/.projectfs/env

if [ -f $config_path ];
then
  read -e -p "Configuration exists. Overwrite? " overwrite
  if [[ ! $overwrite =~ ^[Yy]$ ]]
  then
    exit 0
  fi
fi

rm -f $config_path

cat <<EOF
Starting project-fs configuration tool...

This tool will configure your project-fs daemon.
Only the basic options are configured. Sane defaults are in (parenthesis).

EOF

# PROJECT_API_URL
read -e -p "Project API: (https://api.f7ops.com) " project_api
project_api=${project_api:-"https://api.f7ops.com"}

# PROJECT_API_KEY
read -e -p "Project API Key: " project_api_key

cat <<EOF > $config_path
# Attached Resources
PROJECT_API_URL=$project_api
PROJECT_API_KEY=$project_api_key

# Settings
UNSAFE_TLS=$unsafe_tls

EOF

chmod 400 $config_path

systemctl --user restart project-fs.service

